#ifndef MIDI_CONSTANTS_H
#define MIDI_CONSTANTS_H 

/*
 * MIDI voice event codes
 */
#define VOICE_NOTE_OFF 0x80
#define VOICE_NOTE_ON 0x90
#define VOICE_POLYPHONIC_PRESSURE 0xA0
#define VOICE_AFTERTOUCH VOICE_POLYPHONIC_PRESSURE
#define VOICE_CONTROLLER_CHANGE 0xB0
#define VOICE_PROGRAM_CHANGE 0xC0
#define VOICE_CHANNEL_KEY_PRESSURE 0xD0
#define VOICE_PITCH_BEND 0xE0

/*
 * MIDI voice channel codes
 */
#define CHANNEL_0 0x00
#define CHANNEL_1 0x01
#define CHANNEL_2 0x02
#define CHANNEL_3 0x03
#define CHANNEL_4 0x04
#define CHANNEL_5 0x05
#define CHANNEL_6 0x06
#define CHANNEL_7 0x07
#define CHANNEL_8 0x08
#define CHANNEL_9 0x09
#define CHANNEL_10 0x0a
#define CHANNEL_11 0x0b
#define CHANNEL_12 0x0c
#define CHANNEL_13 0x0d
#define CHANNEL_14 0x0e
#define CHANNEL_15 0x0f

/*
 * MIDI note references
 */
//negative octave
#define NOTE_CN1	0x00
#define NOTE_CSN1	0x01
#define NOTE_DN1	0x02
#define NOTE_DSN1	0x03
#define NOTE_EN1	0x04
#define NOTE_FN1	0x05
#define NOTE_FSN1	0x06
#define NOTE_GN1	0x07
#define NOTE_GSN1	0x08
#define NOTE_AN1	0x09
#define NOTE_ASN1	0x0a
#define NOTE_BN1	0x0b
//0 octave
#define NOTE_C0	0x0c
#define NOTE_CS0	0x0d
#define NOTE_D0	0x0e
#define NOTE_DS0	0x0f
#define NOTE_E0	0x10
#define NOTE_F0	0x11
#define NOTE_FS0	0x12
#define NOTE_G0	0x13
#define NOTE_GS0	0x14
#define NOTE_A0	0x15
#define NOTE_AS0	0x16
#define NOTE_B0	0x17
//1 octave
#define NOTE_C1	0x18
#define NOTE_CS1	0x19
#define NOTE_D1	0x1a
#define NOTE_DS1	0x1b
#define NOTE_E1	0x1c
#define NOTE_F1	0x1d
#define NOTE_FS1	0x1e
#define NOTE_G1	0x1f
#define NOTE_GS1	0x20
#define NOTE_A1	0x21
#define NOTE_AS1	0x22
#define NOTE_B1	0x23
//2 octave
#define NOTE_C2	0x24
#define NOTE_CS2	0x25
#define NOTE_D2	0x26
#define NOTE_DS2	0x27
#define NOTE_E2	0x28
#define NOTE_F2	0x29
#define NOTE_FS2	0x2a
#define NOTE_G2	0x2b
#define NOTE_GS2	0x2c
#define NOTE_A2	0x2d
#define NOTE_AS2	0x2e
#define NOTE_B2	0x2f
//3 octave
#define NOTE_C3	0x30
#define NOTE_CS3	0x31
#define NOTE_D3	0x32
#define NOTE_DS3	0x33
#define NOTE_E3	0x34
#define NOTE_F3	0x35
#define NOTE_FS3	0x36
#define NOTE_G3	0x37
#define NOTE_GS3	0x38
#define NOTE_A3	0x39
#define NOTE_AS3	0x3a
#define NOTE_B3	0x3b
//4 octave
#define NOTE_C4	0x3c
#define NOTE_CS4	0x3d
#define NOTE_D4	0x3e
#define NOTE_DS4	0x3f
#define NOTE_E4	0x40
#define NOTE_F4	0x41
#define NOTE_FS4	0x42
#define NOTE_G4	0x43
#define NOTE_GS4	0x44
#define NOTE_A4	0x45
#define NOTE_AS4	0x46
#define NOTE_B4	0x47
//5 octave
#define NOTE_C5	0x48
#define NOTE_CS5	0x49
#define NOTE_D5	0x4a
#define NOTE_DS5	0x4b
#define NOTE_E5	0x4c
#define NOTE_F5	0x4d
#define NOTE_FS5	0x4e
#define NOTE_G5	0x4f
#define NOTE_GS5	0x50
#define NOTE_A5	0x51
#define NOTE_AS5	0x52
#define NOTE_B5	0x53
//6 octave
#define NOTE_C6	0x54
#define NOTE_CS6	0x55
#define NOTE_D6	0x56
#define NOTE_DS6	0x57
#define NOTE_E6	0x58
#define NOTE_F6	0x59
#define NOTE_FS6	0x5a
#define NOTE_G6	0x5b
#define NOTE_GS6	0x5c
#define NOTE_A6	0x5d
#define NOTE_AS6	0x5e
#define NOTE_B6	0x5f
//7 octave
#define NOTE_C7	0x60
#define NOTE_CS7	0x61
#define NOTE_D7	0x62
#define NOTE_DS7	0x63
#define NOTE_E7	0x64
#define NOTE_F7	0x65
#define NOTE_FS7	0x66
#define NOTE_G7	0x67
#define NOTE_GS7	0x68
#define NOTE_A7	0x69
#define NOTE_AS7	0x6a
#define NOTE_B7	0x6b
//8 octave
#define NOTE_C8	0x6c
#define NOTE_CS8	0x6d
#define NOTE_D8	0x6e
#define NOTE_DS8	0x6f
#define NOTE_E8	0x70
#define NOTE_F8	0x71
#define NOTE_FS8	0x72
#define NOTE_G8	0x73
#define NOTE_GS8	0x74
#define NOTE_A8	0x75
#define NOTE_AS8	0x76
#define NOTE_B8	0x77
//9 octave
#define NOTE_C9	0x78
#define NOTE_CS9	0x79
#define NOTE_D9	0x7a
#define NOTE_DS9	0x7b
#define NOTE_E9	0x7c
#define NOTE_F9	0x7d
#define NOTE_FS9	0x7e
#define NOTE_G9	0x7f
//Notes beyond this are out of range

/*
 * MIDI voice velocities. Determines the dynamics of a Voice event
 */
#define VELOCITY_ZERO 0x00
#define VELOCITY_LOW 0x01
#define VELOCITY_MEDIUM 0x40
#define VELOCITY_HIGH 0x7F
#define VELOCITY_MAX 0x7F
//in music terms
#define VELOCITY_PIANISSIMO 0x01
#define VELOCITY_MEZZOPIANO 0x20
#define VELOCITY_MEZZOFORTE 0x40
#define VELOCITY_FORTE      0x60
#define VELOCITY_FORTISSIMO 0x7F

/*
 * MIDI meta event codes.
 */
#define META_SEQUENCE_NUMBER 0x00
#define META_TEXT_EVENT 0x01
#define META_COPYRIGHT_NOTICE 0x02
#define META_TRACK_NAME 0x03
#define META_INSTRUMENT_NAME 0x04
#define META_LYRIC 0x05
#define META_MARKER 0x06
#define META_CUE 0x07
#define META_MIDI_CHANNEL_PREFIX 0x20
#define META_END_OF_TRACK 0x2F
#define META_END META_END_OF_TRACK
#define META_SET_TEMPO 0x51
#define META_SMTPE_OFFSET 0x54
#define META_TIME_SIGNATURE 0x58
#define META_KEY_SIGNATURE 0x59
#define META_SEQUENCER_SPECIFIC 0x7F

/*
 * Midi Instrument program codes
 */
#define INSTRUMENT_ACOUSTIC_GRAND_PIANO 1
#define INSTRUMENT_BRIGHT_ACOUSTIC_PIANO 2
#define INSTRUMENT_ELECTRIC_GRAND_PIANO 3
#define INSTRUMENT_HONKY_TONK_PIANO 4
#define INSTRUMENT_RHODES_PIANO 5
#define INSTRUMENT_CHORUSED_PIANO 6
#define INSTRUMENT_HARPSICORD 7
#define INSTRUMENT_CLAVINET 8
#define INSTRUMENT_CELESTA 9
#define INSTRUMENT_GLOCKENSPIEL 10
#define INSTRUMENT_MUSIC_BOX 11
#define INSTRUMENT_VIBRAPHONE 12
#define INSTRUMENT_MARIMBA 13
#define INSTRUMENT_XYLOPHONE 14
#define INSTRUMENT_TUBULAR_BELLS 15
#define INSTRUMENT_DULCIMER 16
#define INSTRUMENT_HAMMOND_ORGAN 17
#define INSTRUMENT_PERCUSSIVE_ORGAN 18
#define INSTRUMENT_ROCK_ORGAN 19
#define INSTRUMENT_CHURCH_ORGAN 20
#define INSTRUMENT_REED_ORGAN 21
#define INSTRUMENT_ACCORDION 22
#define INSTRUMENT_HARMONICA 23
#define INSTRUMENT_TANGO_ACCORDION 24
#define INSTRUMENT_ACOUSTIC_NYLON_GUITAR 25
#define INSTRUMENT_ACOUSTIC_STEEL_GUITAR 26
#define INSTRUMENT_ELECTRIC_JAZZ_GUITAR 27
#define INSTRUMENT_ELECTRIC_CLEAN_GUITAR 28
#define INSTRUMENT_ELECTRIC_MUTED_GUITAR 92
#define INSTRUMENT_OVERDRIVEN_GUITAR 30
#define INSTRUMENT_DISTORTION_GUITAR 31
#define INSTRUMENT_GUITAR_HARMONICS 32
#define INSTRUMENT_ACOUSTIC_BASS 33
#define INSTRUMENT_FINGERED_ELECTRIC_BASS 34
#define INSTRUMENT_PLUCKED_ELECTRIC_BASS 35
#define INSTRUMENT_FRETLESS_BASS 36
#define INSTRUMENT_SLAP_BASS_1 37
#define INSTRUMENT_SLAP_BASS_2 38
#define INSTRUMENT_SYNTH_BASS_1 39
#define INSTRUMENT_SYNTH_BASS_2 40
#define INSTRUMENT_VIOLIN 41
#define INSTRUMENT_VIOLA 42
#define INSTRUMENT_CELLO 43
#define INSTRUMENT_CONTRABASS 44
#define INSTRUMENT_TREMOLO_STRINGS 45
#define INSTRUMENT_PIZZICATO_STRINGS 46
#define INSTRUMENT_ORCHESTRAL_HARP 47
#define INSTRUMENT_TIMPANY 48
#define INSTRUMENT_STRING_ENSEMBLE_1 49
#define INSTRUMENT_STRING_ENSEMBLE_2 50
#define INSTRUMENT_SYNTH_STRINGS_1 51
#define INSTRUMENT_SYNTH_STRINGS_2 52
#define INSTRUMENT_CHOIR_AAH 53
#define INSTRUMENT_CHOIR_OOH 54
#define INSTRUMENT_SYNTH_VOICE 55
#define INSTRUMENT_ORCHESTRAL_HIT 56
#define INSTRUMENT_TRUMPET 57
#define INSTRUMENT_TROMBONE 58
#define INSTRUMENT_TUBA 59
#define INSTRUMENT_MUTED_TRUMPET 60
#define INSTRUMENT_FRENCH_HORN 61
#define INSTRUMENT_BRASS_SECTION 62
#define INSTRUMENT_SYNTH_BRASS_1 63
#define INSTRUMENT_SYNTH_BRASS_2 64
#define INSTRUMENT_SOPRANO_SAX 65
#define INSTRUMENT_ALTO_SAX 66
#define INSTRUMENT_TENOR_SAX 67
#define INSTRUMENT_BARITONE_SAX 68
#define INSTRUMENT_OBOE 69
#define INSTRUMENT_ENGLISH_HORN 70
#define INSTRUMENT_BASSOON 71
#define INSTRUMENT_CLARINET 72
#define INSTRUMENT_PICCOLO 73
#define INSTRUMENT_FLUTE 74
#define INSTRUMENT_RECORDER 75
#define INSTRUMENT_PAN_FLUTE 76
#define INSTRUMENT_BOTTLE_BLOW 77
#define INSTRUMENT_SHAKUHACHI 78
#define INSTRUMENT_WHISTLE 79
#define INSTRUMENT_OCARINA 80
#define INSTRUMENT_SQUARE_WAVE_LEAD 81
#define INSTRUMENT_SAWTOOTH_WAVE_LEAD 82
#define INSTRUMENT_CALLIOPE_LEAD 83
#define INSTRUMENT_CHIFF_LEAD 84
#define INSTRUMENT_CHARANG_LEAD 85
#define INSTRUMENT_VOICE_LEAD 86
#define INSTRUMENT_FIFTHS_LEAD 87
#define INSTRUMENT_BASS_LEAD 88
#define INSTRUMENT_NEW_AGE_PAD 89
#define INSTRUMENT_WARM_PAD 90
#define INSTRUMENT_POLYSYNTH_PAD 91
#define INSTRUMENT_CHOIR_PAD 92
#define INSTRUMENT_BOWED_PAD 93
#define INSTRUMENT_METALLIC_PAD 94
#define INSTRUMENT_HALO_PAD 95
#define INSTRUMENT_SWEEP_PAD 96
#define INSTRUMENT_RAIN_EFFECT 97
#define INSTRUMENT_SOUNDTRACK_EFFECT 98
#define INSTRUMENT_CRYSTAL_EFFECT 99
#define INSTRUMENT_ATMOSPHERE_EFFECT 100
#define INSTRUMENT_BRIGHTNESS_EFFECT 101
#define INSTRUMENT_GOBLINS_EFFECT 102
#define INSTRUMENT_ECHOES_EFFECT 103
#define INSTRUMENT_SCIFI_EFFECT 104
#define INSTRUMENT_SITAR 105
#define INSTRUMENT_BANJO 106
#define INSTRUMENT_SHAMISEN 107
#define INSTRUMENT_KOTO 108
#define INSTRUMENT_KALIMBA 109
#define INSTRUMENT_BAGPIPE 110
#define INSTRUMENT_FIDDLE 111
#define INSTRUMENT_SHANAI 112
#define INSTRUMENT_TINKLE_BELL 113
#define INSTRUMENT_AGOGO 114
#define INSTRUMENT_STEEL_DRUMS 115
#define INSTRUMENT_WOODBLOCK 116
#define INSTRUMENT_TAIKO_DRUM 117
#define INSTRUMENT_MELODIC_TOM 118
#define INSTRUMENT_SYNTH_DRUM 119
#define INSTRUMENT_REVERSE_CYMBAL 120
#define INSTRUMENT_GUITAR_FRET_NOISE 121
#define INSTRUMENT_BREATH_NOISE 122
#define INSTRUMENT_SEASHORE 123
#define INSTRUMENT_BIRD_TWEET 124
#define INSTRUMENT_TELEPHONE_RING 125
#define INSTRUMENT_HELICOPTER 126
#define INSTRUMENT_APPLAUSE 127
#define INSTRUMENT_GUNSHOT 128

/*
 * Midi note percussion instruments.
 *
 * When on track 10, Midi notes play percussion instead of the standard notes.
 */
#define PERCUSSION_NOTE_ACOUSTIC_BASS_DRUM 35
#define PERCUSSION_NOTE_BASS_DRUM_1 36
#define PERCUSSION_NOTE_SIDE_STICK 37
#define PERCUSSION_NOTE_ACOUSTIC_SNARE 38
#define PERCUSSION_NOTE_HAND_CLAP 39
#define PERCUSSION_NOTE_ELECTRIC_SNARE 40
#define PERCUSSION_NOTE_LOW_FLOOR_TOM 41
#define PERCUSSION_NOTE_CLOSED_HIGH_HAT 42
#define PERCUSSION_NOTE_HIGH_FLOOR_TOM 43
#define PERCUSSION_NOTE_PEDAL_HIGH_HAT 44
#define PERCUSSION_NOTE_LOW_TOM 45
#define PERCUSSION_NOTE_OPEN_HIGH_HAT 46
#define PERCUSSION_NOTE_LOW_MID_TOM 47
#define PERCUSSION_NOTE_HIGH_MID_TOM 48
#define PERCUSSION_NOTE_CRASH_CYMBAL_1 49
#define PERCUSSION_NOTE_HIGH_TOM 50
#define PERCUSSION_NOTE_RIDE_CYMBAL_1 51
#define PERCUSSION_NOTE_CHINESE_CYMBAL 52
#define PERCUSSION_NOTE_RIDE_BELL 53
#define PERCUSSION_NOTE_TAMBOURINE 54
#define PERCUSSION_NOTE_SPLASH_CYMBAL 55
#define PERCUSSION_NOTE_COWBELL 56
#define PERCUSSION_NOTE_CRASH_CYMBAL_2 57
#define PERCUSSION_NOTE_VIBRASLAP 58
#define PERCUSSION_NOTE_RIDE_CYMBAL_2 59
#define PERCUSSION_NOTE_HIGH_BONGO 60
#define PERCUSSION_NOTE_LOW_BONGO 61
#define PERCUSSION_NOTE_MUTE_HIGH_CONGA 62
#define PERCUSSION_NOTE_OPEN_HIGH_CONGA 63
#define PERCUSSION_NOTE_LOW_CONGA 64
#define PERCUSSION_NOTE_HIGH_TIMBALE 65
#define PERCUSSION_NOTE_LOW_TIMBALE 66
#define PERCUSSION_NOTE_HIGH_AGOGO 67
#define PERCUSSION_NOTE_LOW_AGOGO 68
#define PERCUSSION_NOTE_CABASA 69
#define PERCUSSION_NOTE_MARACAS 70
#define PERCUSSION_NOTE_SHORT_WHISTLE 71
#define PERCUSSION_NOTE_LONG_WHISTLE 72
#define PERCUSSION_NOTE_SHORT_GUIRO 73
#define PERCUSSION_NOTE_LONG_GUIRO 74
#define PERCUSSION_NOTE_CLAVES 75
#define PERCUSSION_NOTE_HIGH_WOOD_BLOCK 76
#define PERCUSSION_NOTE_LOW_WOOD_BLOCK 77
#define PERCUSSION_NOTE_MUTE_CUICA 78
#define PERCUSSION_NOTE_OPEN_CUICA 79
#define PERCUSSION_NOTE_MUTE_TRIANGLE 80
#define PERCUSSION_NOTE_OPEN_TRIANGLE 84

#endif /* MIDI_CONSTANTS_H */
